# Generated by Django 4.1.6 on 2023-02-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysitev1", "0003_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_daate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_daate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
