# Generated by Django 4.1.6 on 2023-02-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysitev1", "0004_answer_modify_daate_question_modify_daate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="modify_daate",
            new_name="modify_date",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="modify_daate",
            new_name="modify_date",
        ),
    ]
